import { fileURLToPath } from "node:url";
import { drizzle, type NodePgDatabase } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { PostgresSaver } from "@langchain/langgraph-checkpoint-postgres";
import pg from "pg";
import { ConfigError } from "@banglaclaw/shared";
import * as schema from "./schema.js";
import { PostgresRunStore } from "./runs.js";
import { PostgresSessionStore } from "./sessions.js";

export type Database = NodePgDatabase<typeof schema>;

/** Generated by drizzle-kit (`pnpm --filter @banglaclaw/storage db:generate`); resolves from src/ and dist/. */
const MIGRATIONS_FOLDER = fileURLToPath(new URL("../drizzle", import.meta.url));

export interface PostgresStorageOptions {
  /** Max pool connections. Default 10. */
  maxConnections?: number;
}

/**
 * PostgreSQL persistence: sessions, messages, runs, tool calls (Drizzle) and LangGraph
 * checkpoints (PostgresSaver), sharing one connection pool.
 */
export class PostgresStorage {
  readonly pool: pg.Pool;
  readonly db: Database;
  readonly sessions: PostgresSessionStore;
  readonly runs: PostgresRunStore;
  #checkpointer: PostgresSaver | undefined;

  constructor(databaseUrl: string, options: PostgresStorageOptions = {}) {
    if (!/^postgres(ql)?:\/\//.test(databaseUrl)) {
      throw new ConfigError("DATABASE_URL must be a postgres:// or postgresql:// URL");
    }
    this.pool = new pg.Pool({ connectionString: databaseUrl, max: options.maxConnections ?? 10 });
    this.db = drizzle(this.pool, { schema });
    this.sessions = new PostgresSessionStore(this.db);
    this.runs = new PostgresRunStore(this.db);
  }

  get checkpointer(): PostgresSaver {
    this.#checkpointer ??= new PostgresSaver(this.pool);
    return this.#checkpointer;
  }

  /** Applies pending schema migrations and creates checkpoint tables. Idempotent. */
  async migrate(): Promise<void> {
    await migrate(this.db, { migrationsFolder: MIGRATIONS_FOLDER });
    await this.checkpointer.setup();
  }

  /** Names of applied Drizzle migrations vs. those shipped with this build. */
  async migrationStatus(): Promise<{ applied: number; available: number }> {
    const { readMigrationFiles } = await import("drizzle-orm/migrator");
    const available = readMigrationFiles({ migrationsFolder: MIGRATIONS_FOLDER }).length;
    try {
      const result = await this.pool.query<{ n: string }>('SELECT count(*)::text AS n FROM drizzle."__drizzle_migrations"');
      return { applied: Number(result.rows[0]?.n ?? 0), available };
    } catch {
      return { applied: 0, available };
    }
  }

  async ping(): Promise<void> {
    await this.pool.query("SELECT 1");
  }

  async close(): Promise<void> {
    await this.pool.end();
  }
}
