import { stringify } from "yaml";

export type ProviderChoice = "openai" | "anthropic" | "local";

export interface InitAnswers {
  provider: ProviderChoice;
  model: string;
  baseUrl?: string;
  storage: "memory" | "postgres";
  knowledge?: { sources: string[]; vectorStore: "memory" | "qdrant"; qdrantUrl?: string };
  longTermMemory?: boolean;
  telegram?: { allowedUserIds: string[] };
  agents?: boolean;
  handoff?: boolean;
  timezone?: string;
}

export const DEFAULT_MODELS: Record<ProviderChoice, string> = {
  openai: "gpt-4o-mini",
  anthropic: "claude-sonnet-5",
  local: "qwen2.5",
};

/** Builds banglaclaw.yaml from wizard answers (secrets are never written here). */
export function buildConfigYaml(a: InitAnswers): string {
  const config: Record<string, unknown> = {
    agent: { name: "banglaclaw" },
    models: {
      default: {
        provider: a.provider === "anthropic" ? "anthropic" : "openai-compatible",
        model: a.model,
        ...(a.provider === "local" && a.baseUrl !== undefined && { baseUrl: a.baseUrl }),
      },
    },
    tools: { allow: ["calculator", "current_datetime", "search_knowledge", "remember", "recall", "forget"] },
    storage: { provider: a.storage },
    ...(a.longTermMemory === true && { memory: { longTerm: { enabled: true } } }),
    ...(a.knowledge !== undefined && {
      knowledge: {
        enabled: true,
        vectorStore: a.knowledge.vectorStore,
        ...(a.knowledge.vectorStore === "qdrant" && { vectorStoreUrl: a.knowledge.qdrantUrl ?? "http://localhost:56333" }),
        sources: a.knowledge.sources,
      },
    }),
    ...(a.provider === "local" && a.knowledge !== undefined && a.baseUrl !== undefined && { embeddings: { model: "bge-m3", baseUrl: a.baseUrl } }),
    ...(a.agents === true && { agents: { dirs: ["agents"] } }),
    ...(a.handoff === true && { handoff: { enabled: true } }),
    ...(a.telegram !== undefined && {
      channels: { telegram: { enabled: true, mode: "polling", access: "allowlist", allowedUserIds: a.telegram.allowedUserIds.map(Number) } },
    }),
    timezone: a.timezone ?? "Asia/Dhaka",
  };
  const header = [
    "# BanglaClaw configuration — generated by `banglaclaw init`.",
    "# Secrets (API keys, DATABASE_URL, bot tokens) live in .env, never in this file.",
    "# All options: banglaclaw.example.yaml and docs/16-configuration.md",
    "",
  ].join("\n");
  return header + stringify(config, { lineWidth: 0 });
}

export interface EnvMergeResult {
  text: string;
  added: string[];
  replaced: string[];
  kept: string[];
}

const LINE = /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=/;

function quote(value: string): string {
  return /^[A-Za-z0-9_./:@+-]*$/.test(value) ? value : JSON.stringify(value);
}

/**
 * Adds keys to a .env file. Existing keys are kept unless listed in `overwrite`, so the wizard
 * never silently replaces a secret the user already has.
 */
export function mergeEnv(existing: string, updates: Record<string, string>, overwrite: ReadonlySet<string> = new Set()): EnvMergeResult {
  const lines = existing === "" ? [] : existing.replace(/\n$/, "").split("\n");
  const present = new Map<string, number>();
  lines.forEach((line, i) => {
    const m = LINE.exec(line);
    if (m?.[1] !== undefined) present.set(m[1], i);
  });
  const added: string[] = [];
  const replaced: string[] = [];
  const kept: string[] = [];
  const hasValue = (i: number) => (lines[i]?.split("=").slice(1).join("=").trim() ?? "") !== "";
  for (const [key, value] of Object.entries(updates)) {
    const i = present.get(key);
    if (i === undefined) {
      lines.push(`${key}=${quote(value)}`);
      added.push(key);
    } else if (overwrite.has(key) || !hasValue(i)) {
      lines[i] = `${key}=${quote(value)}`;
      replaced.push(key);
    } else {
      kept.push(key);
    }
  }
  return { text: `${lines.join("\n")}\n`, added, replaced, kept };
}

/** Existing keys with a non-empty value. */
export function envKeys(text: string): Set<string> {
  const keys = new Set<string>();
  for (const line of text.split("\n")) {
    const m = LINE.exec(line);
    if (m?.[1] !== undefined && line.split("=").slice(1).join("=").trim() !== "") keys.add(m[1]);
  }
  return keys;
}
